import { test, expect } from "@playwright/test";
import fs from "node:fs";
const env = fs.readFileSync(".env.local", "utf8");
const passphrase = env.match(/^ADMIN_PASSPHRASE=(.+)$/m)?.[1] ?? "";

test("public display, sharing, preferences, and calendar", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/");
  await expect(page.getByText("Shared clock", { exact: true })).toBeVisible();
  await expect(page.getByRole("timer")).not.toHaveAttribute("aria-label", "Loading timer");
  await page.getByRole("button", { name: "Share", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page.locator(".qr-container svg")).toBeVisible();
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Display settings", exact: true }).last().click();
  await page.getByRole("button", { name: "Switch theme" }).click();
  await expect(page.locator("html")).toHaveAttribute("data-theme", "light");
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "View schedule" }).click();
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "Add to calendar" }).click();
  expect((await download).suggestedFilename()).toBe("neuraldao.ics");
  await page.keyboard.press("Escape");
  await page.goto("/display");
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
  await expect(page.getByRole("timer")).toBeVisible();
  expect(errors).toEqual([]);
});

test("responsive phone and projector views fit without overflow", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  await expect(page.getByText("Shared clock", { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "artifacts/mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto("/display");
  await expect(page.getByText("Shared clock", { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight)).toBe(true);
  await page.screenshot({ path: "artifacts/projector.png", fullPage: true });
});

test("organizer auth, shared announcements, live changes, and stale revision", async ({ page, browser }) => {
  const response = await page.request.get("/api/admin/event"); expect(response.status()).toBe(401);
  await page.goto("/admin");
  await page.getByLabel("Organizer passphrase").fill(passphrase);
  await page.getByRole("button", { name: "Open controls" }).click();
  await expect(page.getByRole("heading", { name: "Run the room." })).toBeVisible();
  await expect(page.getByText("Connected", { exact: true })).toBeVisible();
  const secondContext = await browser.newContext(); const second = await secondContext.newPage();
  await second.goto("/"); await expect(second.getByText("Shared clock", { exact: true })).toBeVisible();
  await page.getByLabel("Message", { exact: true }).fill("Please save your work. Demo review in 15 minutes.");
  await page.getByRole("button", { name: "Publish", exact: true }).click();
  await expect(second.getByText("Please save your work. Demo review in 15 minutes.", { exact: true })).toBeVisible({ timeout: 12000 });
  const original = await (await page.request.get("/api/admin/event")).json();
  const origin = "http://localhost:3000";
  const announcement = await page.request.post("/api/admin/event", { headers: { origin }, data: { kind: "announcement", revision: original.revision, text: "Concurrency check" } }); expect(announcement.ok()).toBe(true);
  const stale = await page.request.post("/api/admin/event", { headers: { origin }, data: { kind: "announcement", revision: original.revision, text: "Stale write" } }); expect(stale.status()).toBe(409);
  await page.getByLabel("Venue", { exact: true }).fill("Local draft venue");
  let competing = await (await page.request.get("/api/admin/event")).json();
  await page.request.post("/api/admin/event", { headers: { origin }, data: { kind: "config", revision: competing.revision, config: { ...competing.config, venue: "Other organizer venue" } } });
  await page.waitForTimeout(3500);
  await page.getByRole("button", { name: "Save event", exact: true }).click();
  await expect(page.getByText("Another organizer changed the event. Refresh and try again.")).toBeVisible();
  expect((await (await page.request.get("/api/admin/event")).json()).config.venue).toBe("Other organizer venue");
  await page.getByRole("button", { name: "Discard edits", exact: true }).click();
  const invalidOrigin = await page.request.post("/api/admin/event", { headers: { origin: "https://example.com" }, data: { kind: "command", revision: original.revision, command: "reset" } }); expect(invalidOrigin.status()).toBe(403);
  let current = await (await page.request.get("/api/admin/event")).json();
  const start = Date.now() - 60_000; const finish = Date.now() + 2 * 3600_000;
  await page.request.post("/api/admin/event", { headers: { origin }, data: { kind: "config", revision: current.revision, config: { ...current.config, startAt: start, endAt: finish } } });
  await expect(page.getByRole("button", { name: "Pause clock" })).toBeVisible({ timeout: 12000 });
  await page.getByRole("button", { name: "Pause clock" }).click();
  await page.getByRole("button", { name: "Confirm change" }).click();
  await expect(second.getByRole("heading", { name: "Clock paused." })).toBeVisible({ timeout: 12000 });
  const frozen = await second.getByRole("timer").getAttribute("aria-label"); await second.waitForTimeout(1200); expect(await second.getByRole("timer").getAttribute("aria-label")).toBe(frozen);
  await page.getByRole("button", { name: "Resume clock" }).click(); await page.getByRole("button", { name: "Confirm change" }).click();
  await expect(second.getByRole("heading", { name: "Time remaining." })).toBeVisible({ timeout: 12000 });
  await secondContext.setOffline(true); await expect(second.getByText("Connection lost; showing last sync")).toBeVisible({ timeout: 12000 });
  await secondContext.setOffline(false); await expect(second.getByText("Shared clock", { exact: true })).toBeVisible({ timeout: 12000 });
  current = await (await page.request.get("/api/admin/event")).json();
  const { initialEvent } = await import("../../lib/clock");
  const restore = await page.request.post("/api/admin/event", { headers: { origin }, data: { kind: "config", revision: current.revision, config: initialEvent().config } });
  current = await restore.json();
  await page.request.post("/api/admin/event", { headers: { origin }, data: { kind: "announcement", revision: current.revision, text: null } });
  await secondContext.close();
});
